# Generated by Django 2.0.2 on 2019-10-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='应用名称')),
                ('path', models.FilePathField(max_length=120, verbose_name='对应路径')),
                ('enter_file', models.CharField(max_length=120, verbose_name='入口文件')),
                ('exit_file', models.CharField(max_length=120, verbose_name='出口文件')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('automationGroupLevelFirst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automationGroupscript', to='api_test.AutomationGroupLevelFirst', verbose_name='所属用例一级分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '应用对应的脚本',
                'verbose_name_plural': '应用对应的脚本文件',
                'db_table': 'db_application',
            },
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='permissionType',
            field=models.CharField(choices=[('超级管理员', '超级管理员'), ('开发人员', '开发人员'), ('测试人员', '测试人员'), ('邮件发送员', '邮件发送员')], max_length=50, verbose_name='权限角色'),
        ),
    ]
