# Generated by Django 2.0.2 on 2019-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20191012_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscript',
            name='path',
            field=models.CharField(max_length=120, verbose_name='对应路径'),
        ),
    ]
