# Generated by Django 2.0.2 on 2019-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20191012_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscript',
            name='exit_file',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='出口文件'),
        ),
    ]
