# Generated by Django 2.0.2 on 2019-10-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0004_auto_20191014_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationscript',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createUserScript', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
