# Generated by Django 2.0.2 on 2019-10-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_applicationscript_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=120, verbose_name='用例名称')),
                ('test_result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('ERROR', 'ERROR')], max_length=50, verbose_name='测试结果')),
                ('case_test_log', models.CharField(max_length=1024, verbose_name='用例测试日志')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicationScript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_script', to='api_test.ApplicationScript', verbose_name='用例所对应的脚本')),
            ],
            options={
                'verbose_name': '脚本的用例',
                'verbose_name_plural': '脚本的用例文件',
                'db_table': 'db_scriptcase',
            },
        ),
    ]
