# Generated by Django 2.0.2 on 2019-10-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_automationparameterpath_automationparameterquery'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automationparameterpath',
            table='db_path',
        ),
        migrations.AlterModelTable(
            name='automationparameterquery',
            table='db_path',
        ),
    ]
