# Generated by Django 2.0.2 on 2019-10-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_auto_20191028_1901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automationparameterquery',
            table='db_query',
        ),
    ]
