# Generated by Django 2.0.2 on 2019-10-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_auto_20191028_1901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automationparameterpath',
            table='db_pathpara',
        ),
        migrations.AlterModelTable(
            name='automationparameterquery',
            table='db_querypara',
        ),
    ]
