# Generated by Django 2.0.2 on 2019-10-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0010_auto_20191028_1903'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automationparameterpath',
            table='db_path',
        ),
        migrations.AlterModelTable(
            name='automationparameterquery',
            table='db_query',
        ),
    ]
