# Generated by Django 2.0.2 on 2019-10-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_auto_20191028_1933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automationparameterpath',
            table=None,
        ),
        migrations.AlterModelTable(
            name='automationparameterquery',
            table=None,
        ),
    ]
