# Generated by Django 2.0.2 on 2019-10-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_auto_20191028_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationparameterpath',
            name='automationCaseApi',
        ),
        migrations.RemoveField(
            model_name='automationparameterquery',
            name='automationCaseApi',
        ),
        migrations.DeleteModel(
            name='AutomationParameterPath',
        ),
        migrations.DeleteModel(
            name='AutomationParameterQuery',
        ),
    ]
