# Generated by Django 2.0.2 on 2019-10-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_automationparameterpath_automationparameterquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationparameterpath',
            options={'verbose_name': 'path接口参数', 'verbose_name_plural': 'path接口参数管理'},
        ),
        migrations.AlterModelOptions(
            name='automationparameterquery',
            options={'verbose_name': 'query接口参数', 'verbose_name_plural': 'query接口参数管理'},
        ),
    ]
