# Generated by Django 2.0.2 on 2019-10-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0015_auto_20191029_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationparameterpath',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterPath', to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationparameterquery',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterQuery', to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
    ]
